"""добавили асс таблицу польз-челлендж

Revision ID: fe0c6872381e
Revises: 22b4e0c7f491
Create Date: 2021-05-02 10:58:46.184828

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe0c6872381e'
down_revision = '22b4e0c7f491'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_to_challenge',
    sa.Column('user', sa.Integer(), nullable=True),
    sa.Column('challenge', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['challenge'], ['challenges.id'], ),
    sa.ForeignKeyConstraint(['user'], ['users.id'], )
    )
    op.drop_column('challenges', 'why')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('challenges', sa.Column('why', sa.VARCHAR(), nullable=True))
    op.drop_table('user_to_challenge')
    # ### end Alembic commands ###
